development: &common
  adapter: mysql
  encoding: utf8
  database: trampoline_dev
  username: root
  password: 
  reconnect: false
  pool: 5

test: &test
  <<: *common
  database: trampoline_test

cucumber:
  <<: *test

production:
  <<: *common
  database: trampoline_production
